version: '3.4'

services:
  scalorsassignmentbackend:
    image: scalorsassignmentbackend
    restart: unless-stopped
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ../src:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    container_name: scalorsassignmentbackend
    depends_on: 
      - scalor_db
  
  scalor_db: 
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: scalor_db

volumes:
  db_data: